### ISSUE TITLE
Dashboard UI

### ISSUE THREAD

**Issue by revgum** [OregonDigital/hyrax-migrator#114]
Create a UI for visualizing the progress of existing migrations and managing failed migrations.

This ticket will act as a place to collect thoughts and spawn additional tickets to breakdown these ideas into specific implementation. 

- [ ] See a list of Works that are in the failed state, give the ability to resume/restart the migration
- [ ] Visualize some metrics about the total number of Works that were migrated, failed, and each intermediate state
- [ ] Give the ability to initiate a bulk migration from a directory in the configured filesystem or S3 bucket

**Comment by lsat12357** [comment]
although this would have been nice to have, we are little low on resources and time at this point.
