### ISSUE TITLE
[EPIC] Create Actors for processing a Work

### ISSUE THREAD

**Issue by revgum** [OregonDigital/hyrax-migrator#23]
- [x] validate the BAG, get the work type from the file and set the `work.env` with details
- [x] read the n-triples, build a graph and persist that in the `work.env`
- [x] crosswalk the metadata from the `work.env`, setting a new env value to a hash used to set the attributes for the new work to be persisted in Hyrax
- [x] identify which AdminSet/Collection and visibility to set for the new work, store this in`work.env` (admin_set relates to the attributes set by the CrosswalkActor)
- [x] upload the original file(s) from bag to the proper location for Hyrax ingest, could be shared storage (BrowseAnything enabled in Hyrax application), store file metadata and paths in `work.env`
- [x] use `work.env`; instantiate a new work from `Hyrax::Migrator.config.registered_models` based on the work type identified, set attributes hash, associate uploaded files to the work, save it, associate the work to the proper collection(s)/admin_sets, set the work as having been published
- [x] Check the published work to see if the metadata matches in Hyrax and the expected filesets have been associated with the work, once finally successful this is the last actor to run.. It is expected that this actor won't pass immediately, it depends on how long it takes Hyrax to fully ingest a work. Also, this actor will depend on a mechanism to query the work and filesets to verify the work is completely migrated. Possibly use the Work type to query its data and related filesets to validate they are complete.

See tickets
#26 
#27 
#28 
#29 
#30 
#31 
#32

**Comment by lsat12357** [comment]
I'm going to close this, now that we have the verification piece in
